
/* =====================================================
   라이프스테이지별 TOP 5 업종
   - 업종별 소비 금액 기준
   - card_transaction을 1회 스캔 후 집계(agg), UNION ALL은 집계 결과(최대 9 row)에만 적용
   ===================================================== */

-- 전체 라이프 스테이지 별
WITH agg AS (
  SELECT
    LIFE_STAGE,
    SUM(IFNULL(INTERIOR_AM, 0))  AS INTERIOR,
    SUM(IFNULL(INSUHOS_AM,  0))  AS INSUHOS,
    SUM(IFNULL(TRVL_AM,     0))  AS TRVL,
    SUM(IFNULL(CULTURE_AM,  0))  AS CULTURE,
    SUM(IFNULL(GROCERY_AM,  0))  AS GROCERY,
    SUM(IFNULL(HOS_AM,      0))  AS HOSPITAL,
    SUM(IFNULL(RESTRNT_AM,  0))  AS RESTAURANT,
    SUM(IFNULL(FUEL_AM,     0))  AS FUEL
  FROM card_transaction
  GROUP BY LIFE_STAGE
)
SELECT LIFE_STAGE, CATEGORY, TOTAL_AMT, RNK
FROM (
  SELECT
    LIFE_STAGE, CATEGORY, TOTAL_AMT,
    RANK() OVER (PARTITION BY LIFE_STAGE ORDER BY TOTAL_AMT DESC) AS RNK
  FROM (
    SELECT LIFE_STAGE, 'INTERIOR'   AS CATEGORY, INTERIOR   AS TOTAL_AMT FROM agg
    UNION ALL SELECT LIFE_STAGE, 'INSUHOS',    INSUHOS    FROM agg
    UNION ALL SELECT LIFE_STAGE, 'TRVL',       TRVL       FROM agg
    UNION ALL SELECT LIFE_STAGE, 'CULTURE',    CULTURE    FROM agg
    UNION ALL SELECT LIFE_STAGE, 'GROCERY',    GROCERY    FROM agg
    UNION ALL SELECT LIFE_STAGE, 'HOSPITAL',   HOSPITAL   FROM agg
    UNION ALL SELECT LIFE_STAGE, 'RESTAURANT', RESTAURANT FROM agg
    UNION ALL SELECT LIFE_STAGE, 'FUEL',       FUEL       FROM agg
  ) unpivoted
) ranked
WHERE RNK <= 5
ORDER BY LIFE_STAGE, RNK;

-- CHILD_BABY
WITH agg AS (
  SELECT
    LIFE_STAGE,
    SUM(IFNULL(INTERIOR_AM, 0))  AS INTERIOR,
    SUM(IFNULL(INSUHOS_AM,  0))  AS INSUHOS,
    SUM(IFNULL(TRVL_AM,     0))  AS TRVL,
    SUM(IFNULL(CULTURE_AM,  0))  AS CULTURE,
    SUM(IFNULL(GROCERY_AM,  0))  AS GROCERY,
    SUM(IFNULL(HOS_AM,      0))  AS HOSPITAL,
    SUM(IFNULL(RESTRNT_AM,  0))  AS RESTAURANT,
    SUM(IFNULL(FUEL_AM,     0))  AS FUEL
  FROM card_transaction
  WHERE LIFE_STAGE = 'CHILD_BABY'
  GROUP BY LIFE_STAGE
)
SELECT LIFE_STAGE, CATEGORY, TOTAL_AMT, RNK
FROM (
  SELECT
    LIFE_STAGE, CATEGORY, TOTAL_AMT,
    RANK() OVER (PARTITION BY LIFE_STAGE ORDER BY TOTAL_AMT DESC) AS RNK
  FROM (
    SELECT LIFE_STAGE, 'INTERIOR'   AS CATEGORY, INTERIOR   AS TOTAL_AMT FROM agg
    UNION ALL SELECT LIFE_STAGE, 'INSUHOS',    INSUHOS    FROM agg
    UNION ALL SELECT LIFE_STAGE, 'TRVL',       TRVL       FROM agg
    UNION ALL SELECT LIFE_STAGE, 'CULTURE',    CULTURE    FROM agg
    UNION ALL SELECT LIFE_STAGE, 'GROCERY',    GROCERY    FROM agg
    UNION ALL SELECT LIFE_STAGE, 'HOSPITAL',   HOSPITAL   FROM agg
    UNION ALL SELECT LIFE_STAGE, 'RESTAURANT', RESTAURANT FROM agg
    UNION ALL SELECT LIFE_STAGE, 'FUEL',       FUEL       FROM agg
  ) unpivoted
) ranked
WHERE RNK <= 5
ORDER BY LIFE_STAGE, RNK;

-- CHILD_TEEN
WITH agg AS (
  SELECT
    LIFE_STAGE,
    SUM(IFNULL(INTERIOR_AM, 0))  AS INTERIOR,
    SUM(IFNULL(INSUHOS_AM,  0))  AS INSUHOS,
    SUM(IFNULL(TRVL_AM,     0))  AS TRVL,
    SUM(IFNULL(CULTURE_AM,  0))  AS CULTURE,
    SUM(IFNULL(GROCERY_AM,  0))  AS GROCERY,
    SUM(IFNULL(HOS_AM,      0))  AS HOSPITAL,
    SUM(IFNULL(RESTRNT_AM,  0))  AS RESTAURANT,
    SUM(IFNULL(FUEL_AM,     0))  AS FUEL
  FROM card_transaction
  WHERE LIFE_STAGE = 'CHILD_TEEN'
  GROUP BY LIFE_STAGE
)
SELECT LIFE_STAGE, CATEGORY, TOTAL_AMT, RNK
FROM (
  SELECT
    LIFE_STAGE, CATEGORY, TOTAL_AMT,
    RANK() OVER (PARTITION BY LIFE_STAGE ORDER BY TOTAL_AMT DESC) AS RNK
  FROM (
    SELECT LIFE_STAGE, 'INTERIOR'   AS CATEGORY, INTERIOR   AS TOTAL_AMT FROM agg
    UNION ALL SELECT LIFE_STAGE, 'INSUHOS',    INSUHOS    FROM agg
    UNION ALL SELECT LIFE_STAGE, 'TRVL',       TRVL       FROM agg
    UNION ALL SELECT LIFE_STAGE, 'CULTURE',    CULTURE    FROM agg
    UNION ALL SELECT LIFE_STAGE, 'GROCERY',    GROCERY    FROM agg
    UNION ALL SELECT LIFE_STAGE, 'HOSPITAL',   HOSPITAL   FROM agg
    UNION ALL SELECT LIFE_STAGE, 'RESTAURANT', RESTAURANT FROM agg
    UNION ALL SELECT LIFE_STAGE, 'FUEL',       FUEL       FROM agg
  ) unpivoted
) ranked
WHERE RNK <= 5
ORDER BY LIFE_STAGE, RNK;

-- CHILD_UNI
WITH agg AS (
  SELECT
    LIFE_STAGE,
    SUM(IFNULL(INTERIOR_AM, 0))  AS INTERIOR,
    SUM(IFNULL(INSUHOS_AM,  0))  AS INSUHOS,
    SUM(IFNULL(TRVL_AM,     0))  AS TRVL,
    SUM(IFNULL(CULTURE_AM,  0))  AS CULTURE,
    SUM(IFNULL(GROCERY_AM,  0))  AS GROCERY,
    SUM(IFNULL(HOS_AM,      0))  AS HOSPITAL,
    SUM(IFNULL(RESTRNT_AM,  0))  AS RESTAURANT,
    SUM(IFNULL(FUEL_AM,     0))  AS FUEL
  FROM card_transaction
  WHERE LIFE_STAGE = 'CHILD_UNI'
  GROUP BY LIFE_STAGE
)
SELECT LIFE_STAGE, CATEGORY, TOTAL_AMT, RNK
FROM (
  SELECT
    LIFE_STAGE, CATEGORY, TOTAL_AMT,
    RANK() OVER (PARTITION BY LIFE_STAGE ORDER BY TOTAL_AMT DESC) AS RNK
  FROM (
    SELECT LIFE_STAGE, 'INTERIOR'   AS CATEGORY, INTERIOR   AS TOTAL_AMT FROM agg
    UNION ALL SELECT LIFE_STAGE, 'INSUHOS',    INSUHOS    FROM agg
    UNION ALL SELECT LIFE_STAGE, 'TRVL',       TRVL       FROM agg
    UNION ALL SELECT LIFE_STAGE, 'CULTURE',    CULTURE    FROM agg
    UNION ALL SELECT LIFE_STAGE, 'GROCERY',    GROCERY    FROM agg
    UNION ALL SELECT LIFE_STAGE, 'HOSPITAL',   HOSPITAL   FROM agg
    UNION ALL SELECT LIFE_STAGE, 'RESTAURANT', RESTAURANT FROM agg
    UNION ALL SELECT LIFE_STAGE, 'FUEL',       FUEL       FROM agg
  ) unpivoted
) ranked
WHERE RNK <= 5
ORDER BY LIFE_STAGE, RNK;

-- GOLLIFE
WITH agg AS (
  SELECT
    LIFE_STAGE,
    SUM(IFNULL(INTERIOR_AM, 0))  AS INTERIOR,
    SUM(IFNULL(INSUHOS_AM,  0))  AS INSUHOS,
    SUM(IFNULL(TRVL_AM,     0))  AS TRVL,
    SUM(IFNULL(CULTURE_AM,  0))  AS CULTURE,
    SUM(IFNULL(GROCERY_AM,  0))  AS GROCERY,
    SUM(IFNULL(HOS_AM,      0))  AS HOSPITAL,
    SUM(IFNULL(RESTRNT_AM,  0))  AS RESTAURANT,
    SUM(IFNULL(FUEL_AM,     0))  AS FUEL
  FROM card_transaction
  WHERE LIFE_STAGE = 'GOLLIFE'
  GROUP BY LIFE_STAGE
)
SELECT LIFE_STAGE, CATEGORY, TOTAL_AMT, RNK
FROM (
  SELECT
    LIFE_STAGE, CATEGORY, TOTAL_AMT,
    RANK() OVER (PARTITION BY LIFE_STAGE ORDER BY TOTAL_AMT DESC) AS RNK
  FROM (
    SELECT LIFE_STAGE, 'INTERIOR'   AS CATEGORY, INTERIOR   AS TOTAL_AMT FROM agg
    UNION ALL SELECT LIFE_STAGE, 'INSUHOS',    INSUHOS    FROM agg
    UNION ALL SELECT LIFE_STAGE, 'TRVL',       TRVL       FROM agg
    UNION ALL SELECT LIFE_STAGE, 'CULTURE',    CULTURE    FROM agg
    UNION ALL SELECT LIFE_STAGE, 'GROCERY',    GROCERY    FROM agg
    UNION ALL SELECT LIFE_STAGE, 'HOSPITAL',   HOSPITAL   FROM agg
    UNION ALL SELECT LIFE_STAGE, 'RESTAURANT', RESTAURANT FROM agg
    UNION ALL SELECT LIFE_STAGE, 'FUEL',       FUEL       FROM agg
  ) unpivoted
) ranked
WHERE RNK <= 5
ORDER BY LIFE_STAGE, RNK;

-- NEW_JOB
WITH agg AS (
  SELECT
    LIFE_STAGE,
    SUM(IFNULL(INTERIOR_AM, 0))  AS INTERIOR,
    SUM(IFNULL(INSUHOS_AM,  0))  AS INSUHOS,
    SUM(IFNULL(TRVL_AM,     0))  AS TRVL,
    SUM(IFNULL(CULTURE_AM,  0))  AS CULTURE,
    SUM(IFNULL(GROCERY_AM,  0))  AS GROCERY,
    SUM(IFNULL(HOS_AM,      0))  AS HOSPITAL,
    SUM(IFNULL(RESTRNT_AM,  0))  AS RESTAURANT,
    SUM(IFNULL(FUEL_AM,     0))  AS FUEL
  FROM card_transaction
  WHERE LIFE_STAGE = 'NEW_JOB'
  GROUP BY LIFE_STAGE
)
SELECT LIFE_STAGE, CATEGORY, TOTAL_AMT, RNK
FROM (
  SELECT
    LIFE_STAGE, CATEGORY, TOTAL_AMT,
    RANK() OVER (PARTITION BY LIFE_STAGE ORDER BY TOTAL_AMT DESC) AS RNK
  FROM (
    SELECT LIFE_STAGE, 'INTERIOR'   AS CATEGORY, INTERIOR   AS TOTAL_AMT FROM agg
    UNION ALL SELECT LIFE_STAGE, 'INSUHOS',    INSUHOS    FROM agg
    UNION ALL SELECT LIFE_STAGE, 'TRVL',       TRVL       FROM agg
    UNION ALL SELECT LIFE_STAGE, 'CULTURE',    CULTURE    FROM agg
    UNION ALL SELECT LIFE_STAGE, 'GROCERY',    GROCERY    FROM agg
    UNION ALL SELECT LIFE_STAGE, 'HOSPITAL',   HOSPITAL   FROM agg
    UNION ALL SELECT LIFE_STAGE, 'RESTAURANT', RESTAURANT FROM agg
    UNION ALL SELECT LIFE_STAGE, 'FUEL',       FUEL       FROM agg
  ) unpivoted
) ranked
WHERE RNK <= 5
ORDER BY LIFE_STAGE, RNK;

-- RETIRE
WITH agg AS (
  SELECT
    LIFE_STAGE,
    SUM(IFNULL(INTERIOR_AM, 0))  AS INTERIOR,
    SUM(IFNULL(INSUHOS_AM,  0))  AS INSUHOS,
    SUM(IFNULL(TRVL_AM,     0))  AS TRVL,
    SUM(IFNULL(CULTURE_AM,  0))  AS CULTURE,
    SUM(IFNULL(GROCERY_AM,  0))  AS GROCERY,
    SUM(IFNULL(HOS_AM,      0))  AS HOSPITAL,
    SUM(IFNULL(RESTRNT_AM,  0))  AS RESTAURANT,
    SUM(IFNULL(FUEL_AM,     0))  AS FUEL
  FROM card_transaction
  WHERE LIFE_STAGE = 'RETIRE'
  GROUP BY LIFE_STAGE
)
SELECT LIFE_STAGE, CATEGORY, TOTAL_AMT, RNK
FROM (
  SELECT
    LIFE_STAGE, CATEGORY, TOTAL_AMT,
    RANK() OVER (PARTITION BY LIFE_STAGE ORDER BY TOTAL_AMT DESC) AS RNK
  FROM (
    SELECT LIFE_STAGE, 'INTERIOR'   AS CATEGORY, INTERIOR   AS TOTAL_AMT FROM agg
    UNION ALL SELECT LIFE_STAGE, 'INSUHOS',    INSUHOS    FROM agg
    UNION ALL SELECT LIFE_STAGE, 'TRVL',       TRVL       FROM agg
    UNION ALL SELECT LIFE_STAGE, 'CULTURE',    CULTURE    FROM agg
    UNION ALL SELECT LIFE_STAGE, 'GROCERY',    GROCERY    FROM agg
    UNION ALL SELECT LIFE_STAGE, 'HOSPITAL',   HOSPITAL   FROM agg
    UNION ALL SELECT LIFE_STAGE, 'RESTAURANT', RESTAURANT FROM agg
    UNION ALL SELECT LIFE_STAGE, 'FUEL',       FUEL       FROM agg
  ) unpivoted
) ranked
WHERE RNK <= 5
ORDER BY LIFE_STAGE, RNK;

-- SECLIFE
WITH agg AS (
  SELECT
    LIFE_STAGE,
    SUM(IFNULL(INTERIOR_AM, 0))  AS INTERIOR,
    SUM(IFNULL(INSUHOS_AM,  0))  AS INSUHOS,
    SUM(IFNULL(TRVL_AM,     0))  AS TRVL,
    SUM(IFNULL(CULTURE_AM,  0))  AS CULTURE,
    SUM(IFNULL(GROCERY_AM,  0))  AS GROCERY,
    SUM(IFNULL(HOS_AM,      0))  AS HOSPITAL,
    SUM(IFNULL(RESTRNT_AM,  0))  AS RESTAURANT,
    SUM(IFNULL(FUEL_AM,     0))  AS FUEL
  FROM card_transaction
  WHERE LIFE_STAGE = 'SECLIFE'
  GROUP BY LIFE_STAGE
)
SELECT LIFE_STAGE, CATEGORY, TOTAL_AMT, RNK
FROM (
  SELECT
    LIFE_STAGE, CATEGORY, TOTAL_AMT,
    RANK() OVER (PARTITION BY LIFE_STAGE ORDER BY TOTAL_AMT DESC) AS RNK
  FROM (
    SELECT LIFE_STAGE, 'INTERIOR'   AS CATEGORY, INTERIOR   AS TOTAL_AMT FROM agg
    UNION ALL SELECT LIFE_STAGE, 'INSUHOS',    INSUHOS    FROM agg
    UNION ALL SELECT LIFE_STAGE, 'TRVL',       TRVL       FROM agg
    UNION ALL SELECT LIFE_STAGE, 'CULTURE',    CULTURE    FROM agg
    UNION ALL SELECT LIFE_STAGE, 'GROCERY',    GROCERY    FROM agg
    UNION ALL SELECT LIFE_STAGE, 'HOSPITAL',   HOSPITAL   FROM agg
    UNION ALL SELECT LIFE_STAGE, 'RESTAURANT', RESTAURANT FROM agg
    UNION ALL SELECT LIFE_STAGE, 'FUEL',       FUEL       FROM agg
  ) unpivoted
) ranked
WHERE RNK <= 5
ORDER BY LIFE_STAGE, RNK;

-- TEEN
WITH agg AS (
  SELECT
    LIFE_STAGE,
    SUM(IFNULL(INTERIOR_AM, 0))  AS INTERIOR,
    SUM(IFNULL(INSUHOS_AM,  0))  AS INSUHOS,
    SUM(IFNULL(TRVL_AM,     0))  AS TRVL,
    SUM(IFNULL(CULTURE_AM,  0))  AS CULTURE,
    SUM(IFNULL(GROCERY_AM,  0))  AS GROCERY,
    SUM(IFNULL(HOS_AM,      0))  AS HOSPITAL,
    SUM(IFNULL(RESTRNT_AM,  0))  AS RESTAURANT,
    SUM(IFNULL(FUEL_AM,     0))  AS FUEL
  FROM card_transaction
  WHERE LIFE_STAGE = 'TEEN'
  GROUP BY LIFE_STAGE
)
SELECT LIFE_STAGE, CATEGORY, TOTAL_AMT, RNK
FROM (
  SELECT
    LIFE_STAGE, CATEGORY, TOTAL_AMT,
    RANK() OVER (PARTITION BY LIFE_STAGE ORDER BY TOTAL_AMT DESC) AS RNK
  FROM (
    SELECT LIFE_STAGE, 'INTERIOR'   AS CATEGORY, INTERIOR   AS TOTAL_AMT FROM agg
    UNION ALL SELECT LIFE_STAGE, 'INSUHOS',    INSUHOS    FROM agg
    UNION ALL SELECT LIFE_STAGE, 'TRVL',       TRVL       FROM agg
    UNION ALL SELECT LIFE_STAGE, 'CULTURE',    CULTURE    FROM agg
    UNION ALL SELECT LIFE_STAGE, 'GROCERY',    GROCERY    FROM agg
    UNION ALL SELECT LIFE_STAGE, 'HOSPITAL',   HOSPITAL   FROM agg
    UNION ALL SELECT LIFE_STAGE, 'RESTAURANT', RESTAURANT FROM agg
    UNION ALL SELECT LIFE_STAGE, 'FUEL',       FUEL       FROM agg
  ) unpivoted
) ranked
WHERE RNK <= 5
ORDER BY LIFE_STAGE, RNK;

-- UNI
WITH agg AS (
  SELECT
    LIFE_STAGE,
    SUM(IFNULL(INTERIOR_AM, 0))  AS INTERIOR,
    SUM(IFNULL(INSUHOS_AM,  0))  AS INSUHOS,
    SUM(IFNULL(TRVL_AM,     0))  AS TRVL,
    SUM(IFNULL(CULTURE_AM,  0))  AS CULTURE,
    SUM(IFNULL(GROCERY_AM,  0))  AS GROCERY,
    SUM(IFNULL(HOS_AM,      0))  AS HOSPITAL,
    SUM(IFNULL(RESTRNT_AM,  0))  AS RESTAURANT,
    SUM(IFNULL(FUEL_AM,     0))  AS FUEL
  FROM card_transaction
  WHERE LIFE_STAGE = 'UNI'
  GROUP BY LIFE_STAGE
)
SELECT LIFE_STAGE, CATEGORY, TOTAL_AMT, RNK
FROM (
  SELECT
    LIFE_STAGE, CATEGORY, TOTAL_AMT,
    RANK() OVER (PARTITION BY LIFE_STAGE ORDER BY TOTAL_AMT DESC) AS RNK
  FROM (
    SELECT LIFE_STAGE, 'INTERIOR'   AS CATEGORY, INTERIOR   AS TOTAL_AMT FROM agg
    UNION ALL SELECT LIFE_STAGE, 'INSUHOS',    INSUHOS    FROM agg
    UNION ALL SELECT LIFE_STAGE, 'TRVL',       TRVL       FROM agg
    UNION ALL SELECT LIFE_STAGE, 'CULTURE',    CULTURE    FROM agg
    UNION ALL SELECT LIFE_STAGE, 'GROCERY',    GROCERY    FROM agg
    UNION ALL SELECT LIFE_STAGE, 'HOSPITAL',   HOSPITAL   FROM agg
    UNION ALL SELECT LIFE_STAGE, 'RESTAURANT', RESTAURANT FROM agg
    UNION ALL SELECT LIFE_STAGE, 'FUEL',       FUEL       FROM agg
  ) unpivoted
) ranked
WHERE RNK <= 5
ORDER BY LIFE_STAGE, RNK;


/* =====================================================
   특정 라이프스테이지가 유독 많이 쓰는 업종
   - 전체 평균 대비 소비 비율
   - 개선: card_transaction을 1회 스캔(single_scan CTE),
           UNION ALL은 집계 결과(1 row)에만 적용
   ===================================================== */
WITH single_scan AS (
  SELECT
    AVG(CASE WHEN LIFE_STAGE = 'NEW_JOB' THEN INTERIOR_AM END)  AS nj_interior,
    AVG(CASE WHEN LIFE_STAGE = 'NEW_JOB' THEN INSUHOS_AM  END)  AS nj_insuhos,
    AVG(CASE WHEN LIFE_STAGE = 'NEW_JOB' THEN TRVL_AM     END)  AS nj_trvl,
    AVG(CASE WHEN LIFE_STAGE = 'NEW_JOB' THEN CULTURE_AM  END)  AS nj_culture,
    AVG(CASE WHEN LIFE_STAGE = 'NEW_JOB' THEN GROCERY_AM  END)  AS nj_grocery,
    AVG(CASE WHEN LIFE_STAGE = 'NEW_JOB' THEN HOS_AM      END)  AS nj_hospital,
    AVG(CASE WHEN LIFE_STAGE = 'NEW_JOB' THEN RESTRNT_AM  END)  AS nj_restaurant,
    AVG(CASE WHEN LIFE_STAGE = 'NEW_JOB' THEN FUEL_AM     END)  AS nj_fuel,
    AVG(INTERIOR_AM)  AS total_interior,
    AVG(INSUHOS_AM)   AS total_insuhos,
    AVG(TRVL_AM)      AS total_trvl,
    AVG(CULTURE_AM)   AS total_culture,
    AVG(GROCERY_AM)   AS total_grocery,
    AVG(HOS_AM)       AS total_hospital,
    AVG(RESTRNT_AM)   AS total_restaurant,
    AVG(FUEL_AM)      AS total_fuel
  FROM card_transaction
)
SELECT
  CATEGORY,
  TARGET_AVG,
  TOTAL_AVG,
  ROUND(TARGET_AVG / NULLIF(TOTAL_AVG, 0), 2) AS RELATIVE_RATIO
FROM (
  SELECT 'INTERIOR'   AS CATEGORY, nj_interior,   total_interior   FROM single_scan
  UNION ALL SELECT 'INSUHOS',    nj_insuhos,    total_insuhos    FROM single_scan
  UNION ALL SELECT 'TRVL',       nj_trvl,       total_trvl       FROM single_scan
  UNION ALL SELECT 'CULTURE',    nj_culture,    total_culture    FROM single_scan
  UNION ALL SELECT 'GROCERY',    nj_grocery,    total_grocery    FROM single_scan
  UNION ALL SELECT 'HOSPITAL',   nj_hospital,   total_hospital   FROM single_scan
  UNION ALL SELECT 'RESTAURANT', nj_restaurant, total_restaurant FROM single_scan
  UNION ALL SELECT 'FUEL',       nj_fuel,       total_fuel       FROM single_scan
) base (CATEGORY, TARGET_AVG, TOTAL_AVG)
WHERE ROUND(TARGET_AVG / NULLIF(TOTAL_AVG, 0), 2) >= 1.3
ORDER BY RELATIVE_RATIO;


/* =====================================================
   라이프스테이지별 필수 vs 선택 소비 구조
   - 필수 : 병원(HOS) 마트(GROCERY) 교통(FUEL)
   - 선택 : 외식(RESTRNT) 여행(TRVL) 문화(CULTURE)
   ===================================================== */
SELECT
  LIFE_STAGE,
  SUM(HOS_AM + GROCERY_AM + FUEL_AM)       AS ESSENTIAL_AMT,
  SUM(RESTRNT_AM + TRVL_AM + CULTURE_AM)   AS OPTIONAL_AMT
FROM card_transaction
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;

-- CHILD_BABY
SELECT
  LIFE_STAGE,
  SUM(HOS_AM + GROCERY_AM + FUEL_AM)       AS ESSENTIAL_AMT,
  SUM(RESTRNT_AM + TRVL_AM + CULTURE_AM)   AS OPTIONAL_AMT
FROM card_transaction
WHERE LIFE_STAGE = 'CHILD_BABY'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;

-- CHILD_TEEN
SELECT
  LIFE_STAGE,
  SUM(HOS_AM + GROCERY_AM + FUEL_AM)       AS ESSENTIAL_AMT,
  SUM(RESTRNT_AM + TRVL_AM + CULTURE_AM)   AS OPTIONAL_AMT
FROM card_transaction
WHERE LIFE_STAGE = 'CHILD_TEEN'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;

-- CHILD_UNI
SELECT
  LIFE_STAGE,
  SUM(HOS_AM + GROCERY_AM + FUEL_AM)       AS ESSENTIAL_AMT,
  SUM(RESTRNT_AM + TRVL_AM + CULTURE_AM)   AS OPTIONAL_AMT
FROM card_transaction
WHERE LIFE_STAGE = 'CHILD_UNI'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;

-- GOLLIFE
SELECT
  LIFE_STAGE,
  SUM(HOS_AM + GROCERY_AM + FUEL_AM)       AS ESSENTIAL_AMT,
  SUM(RESTRNT_AM + TRVL_AM + CULTURE_AM)   AS OPTIONAL_AMT
FROM card_transaction
WHERE LIFE_STAGE = 'GOLLIFE'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;

-- NEW_JOB
SELECT
  LIFE_STAGE,
  SUM(HOS_AM + GROCERY_AM + FUEL_AM)       AS ESSENTIAL_AMT,
  SUM(RESTRNT_AM + TRVL_AM + CULTURE_AM)   AS OPTIONAL_AMT
FROM card_transaction
WHERE LIFE_STAGE = 'NEW_JOB'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;

-- RETIRE
SELECT
  LIFE_STAGE,
  SUM(HOS_AM + GROCERY_AM + FUEL_AM)       AS ESSENTIAL_AMT,
  SUM(RESTRNT_AM + TRVL_AM + CULTURE_AM)   AS OPTIONAL_AMT
FROM card_transaction
WHERE LIFE_STAGE = 'RETIRE'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;

-- SECLIFE
SELECT
  LIFE_STAGE,
  SUM(HOS_AM + GROCERY_AM + FUEL_AM)       AS ESSENTIAL_AMT,
  SUM(RESTRNT_AM + TRVL_AM + CULTURE_AM)   AS OPTIONAL_AMT
FROM card_transaction
WHERE LIFE_STAGE = 'SECLIFE'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;

-- TEEN
SELECT
  LIFE_STAGE,
  SUM(HOS_AM + GROCERY_AM + FUEL_AM)       AS ESSENTIAL_AMT,
  SUM(RESTRNT_AM + TRVL_AM + CULTURE_AM)   AS OPTIONAL_AMT
FROM card_transaction
WHERE LIFE_STAGE = 'TEEN'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;

-- UNI
SELECT
  LIFE_STAGE,
  SUM(HOS_AM + GROCERY_AM + FUEL_AM)       AS ESSENTIAL_AMT,
  SUM(RESTRNT_AM + TRVL_AM + CULTURE_AM)   AS OPTIONAL_AMT
FROM card_transaction
WHERE LIFE_STAGE = 'UNI'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;


/* =====================================================
   라이프스테이지별 신용카드 VS 체크카드 이용 금액 비중
   ===================================================== */
SELECT
    LIFE_STAGE,
    SUM(CRDSL_USE_AM) AS CRDSL_USE_AM,
    SUM(CNF_USE_AM)   AS CNF_USE_AM
FROM card_transaction
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;

-- CHILD_BABY
SELECT
    LIFE_STAGE,
    SUM(CRDSL_USE_AM) AS CRDSL_USE_AM,
    SUM(CNF_USE_AM)   AS CNF_USE_AM
FROM card_transaction
WHERE LIFE_STAGE = 'CHILD_BABY'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;

-- CHILD_TEEN
SELECT
    LIFE_STAGE,
    SUM(CRDSL_USE_AM) AS CRDSL_USE_AM,
    SUM(CNF_USE_AM)   AS CNF_USE_AM
FROM card_transaction
WHERE LIFE_STAGE = 'CHILD_TEEN'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;

-- CHILD_UNI
SELECT
    LIFE_STAGE,
    SUM(CRDSL_USE_AM) AS CRDSL_USE_AM,
    SUM(CNF_USE_AM)   AS CNF_USE_AM
FROM card_transaction
WHERE LIFE_STAGE = 'CHILD_UNI'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;

-- GOLLIFE
SELECT
    LIFE_STAGE,
    SUM(CRDSL_USE_AM) AS CRDSL_USE_AM,
    SUM(CNF_USE_AM)   AS CNF_USE_AM
FROM card_transaction
WHERE LIFE_STAGE = 'GOLLIFE'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;

-- NEW_JOB
SELECT
    LIFE_STAGE,
    SUM(CRDSL_USE_AM) AS CRDSL_USE_AM,
    SUM(CNF_USE_AM)   AS CNF_USE_AM
FROM card_transaction
WHERE LIFE_STAGE = 'NEW_JOB'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;

-- RETIRE
SELECT
    LIFE_STAGE,
    SUM(CRDSL_USE_AM) AS CRDSL_USE_AM,
    SUM(CNF_USE_AM)   AS CNF_USE_AM
FROM card_transaction
WHERE LIFE_STAGE = 'RETIRE'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;

-- SECLIFE
SELECT
    LIFE_STAGE,
    SUM(CRDSL_USE_AM) AS CRDSL_USE_AM,
    SUM(CNF_USE_AM)   AS CNF_USE_AM
FROM card_transaction
WHERE LIFE_STAGE = 'SECLIFE'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;

-- TEEN
SELECT
    LIFE_STAGE,
    SUM(CRDSL_USE_AM) AS CRDSL_USE_AM,
    SUM(CNF_USE_AM)   AS CNF_USE_AM
FROM card_transaction
WHERE LIFE_STAGE = 'TEEN'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;

-- UNI
SELECT
    LIFE_STAGE,
    SUM(CRDSL_USE_AM) AS CRDSL_USE_AM,
    SUM(CNF_USE_AM)   AS CNF_USE_AM
FROM card_transaction
WHERE LIFE_STAGE = 'UNI'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;


/* =====================================================
   라이프스테이지별 회원등급 비율
   ===================================================== */
SELECT
  LIFE_STAGE,
  MBR_RK,
  COUNT(*) AS CNT,
  ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY LIFE_STAGE), 2) AS RATIO_PCT
FROM card_transaction
GROUP BY LIFE_STAGE, MBR_RK
ORDER BY LIFE_STAGE, RATIO_PCT DESC;

-- CHILD_BABY
SELECT
  LIFE_STAGE,
  MBR_RK,
  COUNT(*) AS CNT,
  ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY LIFE_STAGE), 2) AS RATIO_PCT
FROM card_transaction
WHERE LIFE_STAGE = 'CHILD_BABY'
GROUP BY LIFE_STAGE, MBR_RK
ORDER BY LIFE_STAGE, RATIO_PCT DESC;

-- CHILD_TEEN
SELECT
  LIFE_STAGE,
  MBR_RK,
  COUNT(*) AS CNT,
  ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY LIFE_STAGE), 2) AS RATIO_PCT
FROM card_transaction
WHERE LIFE_STAGE = 'CHILD_TEEN'
GROUP BY LIFE_STAGE, MBR_RK
ORDER BY LIFE_STAGE, RATIO_PCT DESC;

-- CHILD_UNI
SELECT
  LIFE_STAGE,
  MBR_RK,
  COUNT(*) AS CNT,
  ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY LIFE_STAGE), 2) AS RATIO_PCT
FROM card_transaction
WHERE LIFE_STAGE = 'CHILD_UNI'
GROUP BY LIFE_STAGE, MBR_RK
ORDER BY LIFE_STAGE, RATIO_PCT DESC;

-- GOLLIFE
SELECT
  LIFE_STAGE,
  MBR_RK,
  COUNT(*) AS CNT,
  ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY LIFE_STAGE), 2) AS RATIO_PCT
FROM card_transaction
WHERE LIFE_STAGE = 'GOLLIFE'
GROUP BY LIFE_STAGE, MBR_RK
ORDER BY LIFE_STAGE, RATIO_PCT DESC;

-- NEW_JOB
SELECT
  LIFE_STAGE,
  MBR_RK,
  COUNT(*) AS CNT,
  ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY LIFE_STAGE), 2) AS RATIO_PCT
FROM card_transaction
WHERE LIFE_STAGE = 'NEW_JOB'
GROUP BY LIFE_STAGE, MBR_RK
ORDER BY LIFE_STAGE, RATIO_PCT DESC;

-- RETIRE
SELECT
  LIFE_STAGE,
  MBR_RK,
  COUNT(*) AS CNT,
  ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY LIFE_STAGE), 2) AS RATIO_PCT
FROM card_transaction
WHERE LIFE_STAGE = 'RETIRE'
GROUP BY LIFE_STAGE, MBR_RK
ORDER BY LIFE_STAGE, RATIO_PCT DESC;

-- SECLIFE
SELECT
  LIFE_STAGE,
  MBR_RK,
  COUNT(*) AS CNT,
  ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY LIFE_STAGE), 2) AS RATIO_PCT
FROM card_transaction
WHERE LIFE_STAGE = 'SECLIFE'
GROUP BY LIFE_STAGE, MBR_RK
ORDER BY LIFE_STAGE, RATIO_PCT DESC;

-- TEEN
SELECT
  LIFE_STAGE,
  MBR_RK,
  COUNT(*) AS CNT,
  ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY LIFE_STAGE), 2) AS RATIO_PCT
FROM card_transaction
WHERE LIFE_STAGE = 'TEEN'
GROUP BY LIFE_STAGE, MBR_RK
ORDER BY LIFE_STAGE, RATIO_PCT DESC;

-- UNI
SELECT
  LIFE_STAGE,
  MBR_RK,
  COUNT(*) AS CNT,
  ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY LIFE_STAGE), 2) AS RATIO_PCT
FROM card_transaction
WHERE LIFE_STAGE = 'UNI'
GROUP BY LIFE_STAGE, MBR_RK
ORDER BY LIFE_STAGE, RATIO_PCT DESC;
