
/* =====================================================
   라이프스테이지별 TOP 5 업종
   - 업종별 소비 금액 기준
   ===================================================== */
-- 전체 라이프 스테이지 별
SELECT *
FROM (
  SELECT
    LIFE_STAGE,
    CATEGORY,
    SUM(AMT) AS TOTAL_AMT,
    RANK() OVER (
      PARTITION BY LIFE_STAGE
      ORDER BY SUM(AMT) DESC
    ) AS RNK
  FROM (
    SELECT LIFE_STAGE, 'INTERIOR'   AS CATEGORY, IFNULL(INTERIOR_AM,0)   AS AMT FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'INSUHOS',   IFNULL(INSUHOS_AM,0)   FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'TRVL',      IFNULL(TRVL_AM,0)      FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'CULTURE',   IFNULL(CULTURE_AM,0)   FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'GROCERY',   IFNULL(GROCERY_AM,0)   FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'HOSPITAL',  IFNULL(HOS_AM,0)       FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'RESTAURANT',IFNULL(RESTRNT_AM,0)   FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'FUEL',      IFNULL(FUEL_AM,0)      FROM card_transaction
  ) t
  GROUP BY LIFE_STAGE, CATEGORY
) r
WHERE RNK <= 5
ORDER BY LIFE_STAGE, RNK;

-- CHILD_BABY
SELECT *
FROM (
  SELECT
    LIFE_STAGE,
    CATEGORY,
    SUM(AMT) AS TOTAL_AMT,
    RANK() OVER (
      PARTITION BY LIFE_STAGE
      ORDER BY SUM(AMT) DESC
    ) AS RNK
  FROM (
    SELECT LIFE_STAGE, 'INTERIOR'   AS CATEGORY, IFNULL(INTERIOR_AM,0)   AS AMT FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'INSUHOS',   IFNULL(INSUHOS_AM,0)   FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'TRVL',      IFNULL(TRVL_AM,0)      FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'CULTURE',   IFNULL(CULTURE_AM,0)   FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'GROCERY',   IFNULL(GROCERY_AM,0)   FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'HOSPITAL',  IFNULL(HOS_AM,0)       FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'RESTAURANT',IFNULL(RESTRNT_AM,0)   FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'FUEL',      IFNULL(FUEL_AM,0)      FROM card_transaction
  ) t
  WHERE LIFE_STAGE='CHILD_BABY'
  GROUP BY LIFE_STAGE, CATEGORY
) r
WHERE RNK <= 5
ORDER BY LIFE_STAGE, RNK;


-- CHILD_TEEN
SELECT *
FROM (
  SELECT
    LIFE_STAGE,
    CATEGORY,
    SUM(AMT) AS TOTAL_AMT,
    RANK() OVER (
      PARTITION BY LIFE_STAGE
      ORDER BY SUM(AMT) DESC
    ) AS RNK
  FROM (
    SELECT LIFE_STAGE, 'INTERIOR'   AS CATEGORY, IFNULL(INTERIOR_AM,0)   AS AMT FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'INSUHOS',   IFNULL(INSUHOS_AM,0)   FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'TRVL',      IFNULL(TRVL_AM,0)      FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'CULTURE',   IFNULL(CULTURE_AM,0)   FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'GROCERY',   IFNULL(GROCERY_AM,0)   FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'HOSPITAL',  IFNULL(HOS_AM,0)       FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'RESTAURANT',IFNULL(RESTRNT_AM,0)   FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'FUEL',      IFNULL(FUEL_AM,0)      FROM card_transaction
  ) t
  WHERE LIFE_STAGE='CHILD_TEEN'
  GROUP BY LIFE_STAGE, CATEGORY
) r
WHERE RNK <= 5
ORDER BY LIFE_STAGE, RNK;


-- CHILD_UNI
SELECT *
FROM (
  SELECT
    LIFE_STAGE,
    CATEGORY,
    SUM(AMT) AS TOTAL_AMT,
    RANK() OVER (
      PARTITION BY LIFE_STAGE
      ORDER BY SUM(AMT) DESC
    ) AS RNK
  FROM (
    SELECT LIFE_STAGE, 'INTERIOR'   AS CATEGORY, IFNULL(INTERIOR_AM,0)   AS AMT FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'INSUHOS',   IFNULL(INSUHOS_AM,0)   FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'TRVL',      IFNULL(TRVL_AM,0)      FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'CULTURE',   IFNULL(CULTURE_AM,0)   FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'GROCERY',   IFNULL(GROCERY_AM,0)   FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'HOSPITAL',  IFNULL(HOS_AM,0)       FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'RESTAURANT',IFNULL(RESTRNT_AM,0)   FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'FUEL',      IFNULL(FUEL_AM,0)      FROM card_transaction
  ) t
  WHERE LIFE_STAGE='CHILD_UNI'
  GROUP BY LIFE_STAGE, CATEGORY
) r
WHERE RNK <= 5
ORDER BY LIFE_STAGE, RNK;

-- GOLLIFE
SELECT *
FROM (
  SELECT
    LIFE_STAGE,
    CATEGORY,
    SUM(AMT) AS TOTAL_AMT,
    RANK() OVER (
      PARTITION BY LIFE_STAGE
      ORDER BY SUM(AMT) DESC
    ) AS RNK
  FROM (
    SELECT LIFE_STAGE, 'INTERIOR'   AS CATEGORY, IFNULL(INTERIOR_AM,0)   AS AMT FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'INSUHOS',   IFNULL(INSUHOS_AM,0)   FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'TRVL',      IFNULL(TRVL_AM,0)      FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'CULTURE',   IFNULL(CULTURE_AM,0)   FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'GROCERY',   IFNULL(GROCERY_AM,0)   FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'HOSPITAL',  IFNULL(HOS_AM,0)       FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'RESTAURANT',IFNULL(RESTRNT_AM,0)   FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'FUEL',      IFNULL(FUEL_AM,0)      FROM card_transaction
  ) t
  WHERE LIFE_STAGE='GOLLIFE'
  GROUP BY LIFE_STAGE, CATEGORY
) r
WHERE RNK <= 5
ORDER BY LIFE_STAGE, RNK;

-- NEW_JOB
SELECT *
FROM (
  SELECT
    LIFE_STAGE,
    CATEGORY,
    SUM(AMT) AS TOTAL_AMT,
    RANK() OVER (
      PARTITION BY LIFE_STAGE
      ORDER BY SUM(AMT) DESC
    ) AS RNK
  FROM (
    SELECT LIFE_STAGE, 'INTERIOR'   AS CATEGORY, IFNULL(INTERIOR_AM,0)   AS AMT FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'INSUHOS',   IFNULL(INSUHOS_AM,0)   FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'TRVL',      IFNULL(TRVL_AM,0)      FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'CULTURE',   IFNULL(CULTURE_AM,0)   FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'GROCERY',   IFNULL(GROCERY_AM,0)   FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'HOSPITAL',  IFNULL(HOS_AM,0)       FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'RESTAURANT',IFNULL(RESTRNT_AM,0)   FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'FUEL',      IFNULL(FUEL_AM,0)      FROM card_transaction
  ) t
  WHERE LIFE_STAGE='NEW_JOB'
  GROUP BY LIFE_STAGE, CATEGORY
) r
WHERE RNK <= 5
ORDER BY LIFE_STAGE, RNK;


-- RETIRE
SELECT *
FROM (
  SELECT
    LIFE_STAGE,
    CATEGORY,
    SUM(AMT) AS TOTAL_AMT,
    RANK() OVER (
      PARTITION BY LIFE_STAGE
      ORDER BY SUM(AMT) DESC
    ) AS RNK
  FROM (
    SELECT LIFE_STAGE, 'INTERIOR'   AS CATEGORY, IFNULL(INTERIOR_AM,0)   AS AMT FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'INSUHOS',   IFNULL(INSUHOS_AM,0)   FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'TRVL',      IFNULL(TRVL_AM,0)      FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'CULTURE',   IFNULL(CULTURE_AM,0)   FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'GROCERY',   IFNULL(GROCERY_AM,0)   FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'HOSPITAL',  IFNULL(HOS_AM,0)       FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'RESTAURANT',IFNULL(RESTRNT_AM,0)   FROM card_transaction
    UNION ALL SELECT LIFE_STAGE, 'FUEL',      IFNULL(FUEL_AM,0)      FROM card_transaction
  ) t
  WHERE LIFE_STAGE='RETIRE'
  GROUP BY LIFE_STAGE, CATEGORY
) r
WHERE RNK <= 5
ORDER BY LIFE_STAGE, RNK;

-- SECLIFE

-- TEEN

-- UNI


/* =====================================================
   특정 라이프스테이지가 유독 많이 쓰는 업종
   - 전체 평균 대비 소비 비율
   ===================================================== */
SELECT
  CATEGORY,
  AVG(CASE WHEN LIFE_STAGE = 'NEW_JOB' THEN AMT END) AS TARGET_AVG,
  AVG(AMT) AS TOTAL_AVG,
  ROUND(
    AVG(CASE WHEN LIFE_STAGE = 'NEW_JOB' THEN AMT END)/ AVG(AMT), 2) AS RELATIVE_RATIO
FROM (
  SELECT LIFE_STAGE, 'INTERIOR' AS CATEGORY, INTERIOR_AM AS AMT FROM card_transaction
  UNION ALL SELECT LIFE_STAGE, 'INSUHOS', INSUHOS_AM FROM card_transaction
  UNION ALL SELECT LIFE_STAGE, 'TRVL', TRVL_AM FROM card_transaction
  UNION ALL SELECT LIFE_STAGE, 'CULTURE', CULTURE_AM FROM card_transaction
  UNION ALL SELECT LIFE_STAGE, 'GROCERY', GROCERY_AM FROM card_transaction
  UNION ALL SELECT LIFE_STAGE, 'HOSPITAL', HOS_AM FROM card_transaction
  UNION ALL SELECT LIFE_STAGE, 'RESTAURANT', RESTRNT_AM FROM card_transaction
  UNION ALL SELECT LIFE_STAGE, 'FUEL', FUEL_AM FROM card_transaction
) t
GROUP BY CATEGORY
HAVING RELATIVE_RATIO >= 1.3
ORDER BY RELATIVE_RATIO;

/* =====================================================
   라이프스테이지별 필수 vs 선택 소비 구조
   - 필수 : 병원(HOST) 마트(GROCERY) 교통(FUEL)
   - 선택 : 외식(RESTRNT) 여행(TRVL) 문화(CULTURE)
   ===================================================== */
SELECT
  LIFE_STAGE,
  SUM(HOS_AM + GROCERY_AM + FUEL_AM)       AS ESSENTIAL_AMT,
  SUM(RESTRNT_AM + TRVL_AM + CULTURE_AM)   AS OPTIONAL_AMT
FROM card_transaction
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;

-- CHILD_BABY
SELECT
  LIFE_STAGE,
  SUM(HOS_AM + GROCERY_AM + FUEL_AM)       AS ESSENTIAL_AMT,
  SUM(RESTRNT_AM + TRVL_AM + CULTURE_AM)   AS OPTIONAL_AMT
FROM card_transaction
WHERE LIFE_STAGE = 'CHILD_BABY'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;

-- CHILD_TEEN
SELECT
  LIFE_STAGE,
  SUM(HOS_AM + GROCERY_AM + FUEL_AM)       AS ESSENTIAL_AMT,
  SUM(RESTRNT_AM + TRVL_AM + CULTURE_AM)   AS OPTIONAL_AMT
FROM card_transaction
WHERE LIFE_STAGE = 'CHILD_TEEN'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;


-- CHILD_UNI
SELECT
  LIFE_STAGE,
  SUM(HOS_AM + GROCERY_AM + FUEL_AM)       AS ESSENTIAL_AMT,
  SUM(RESTRNT_AM + TRVL_AM + CULTURE_AM)   AS OPTIONAL_AMT
FROM card_transaction
WHERE LIFE_STAGE = 'CHILD_UNI'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;

-- GOLLIFE
SELECT
  LIFE_STAGE,
  SUM(HOS_AM + GROCERY_AM + FUEL_AM)       AS ESSENTIAL_AMT,
  SUM(RESTRNT_AM + TRVL_AM + CULTURE_AM)   AS OPTIONAL_AMT
FROM card_transaction
WHERE LIFE_STAGE = 'GOLLIFE'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;

-- NEW_JOB
SELECT
  LIFE_STAGE,
  SUM(HOS_AM + GROCERY_AM + FUEL_AM)       AS ESSENTIAL_AMT,
  SUM(RESTRNT_AM + TRVL_AM + CULTURE_AM)   AS OPTIONAL_AMT
FROM card_transaction
WHERE LIFE_STAGE = 'NEW_JOB'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;

-- RETIRE
SELECT
  LIFE_STAGE,
  SUM(HOS_AM + GROCERY_AM + FUEL_AM)       AS ESSENTIAL_AMT,
  SUM(RESTRNT_AM + TRVL_AM + CULTURE_AM)   AS OPTIONAL_AMT
FROM card_transaction
WHERE LIFE_STAGE = 'RETIRE'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;

-- SECLIFE
SELECT
  LIFE_STAGE,
  SUM(HOS_AM + GROCERY_AM + FUEL_AM)       AS ESSENTIAL_AMT,
  SUM(RESTRNT_AM + TRVL_AM + CULTURE_AM)   AS OPTIONAL_AMT
FROM card_transaction
WHERE LIFE_STAGE = 'SECLIFE'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;

-- TEEN
SELECT
  LIFE_STAGE,
  SUM(HOS_AM + GROCERY_AM + FUEL_AM)       AS ESSENTIAL_AMT,
  SUM(RESTRNT_AM + TRVL_AM + CULTURE_AM)   AS OPTIONAL_AMT
FROM card_transaction
WHERE LIFE_STAGE = 'TEEN'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;

-- UNI
SELECT
  LIFE_STAGE,
  SUM(HOS_AM + GROCERY_AM + FUEL_AM)       AS ESSENTIAL_AMT,
  SUM(RESTRNT_AM + TRVL_AM + CULTURE_AM)   AS OPTIONAL_AMT
FROM card_transaction
WHERE LIFE_STAGE = 'UNI'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;


/* =====================================================
   라이프스테이지별 신용카드 VS 체크카드 이용 금액 비중
   - 필수 : 병원(HOST) 마트(GROCERY) 교통(FUEL)
   - 선택 : 외식(RESTRNT) 여행(TRVL) 문화(CULTURE)
   ===================================================== */
SELECT 
    LIFE_STAGE,
    SUM(CRDSL_USE_AM) AS CRDSL_USE_AM,
    SUM(CNF_USE_AM) AS CNF_USE_AM
FROM card_transaction
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;

-- CHILD_BABY
SELECT 
    LIFE_STAGE,
    SUM(CRDSL_USE_AM) AS CRDSL_USE_AM,
    SUM(CNF_USE_AM) AS CNF_USE_AM
FROM card_transaction
WHERE LIFE_STAGE = 'CHILD_BABY'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;

-- CHILD_TEEN
SELECT 
    LIFE_STAGE,
    SUM(CRDSL_USE_AM) AS CRDSL_USE_AM,
    SUM(CNF_USE_AM) AS CNF_USE_AM
FROM card_transaction
WHERE LIFE_STAGE = 'CHILD_TEEN'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;

-- CHILD_UNI
SELECT 
    LIFE_STAGE,
    SUM(CRDSL_USE_AM) AS CRDSL_USE_AM,
    SUM(CNF_USE_AM) AS CNF_USE_AM
FROM card_transaction
WHERE LIFE_STAGE = 'CHILD_UNI'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;

-- GOLLIFE
SELECT 
    LIFE_STAGE,
    SUM(CRDSL_USE_AM) AS CRDSL_USE_AM,
    SUM(CNF_USE_AM) AS CNF_USE_AM
FROM card_transaction
WHERE LIFE_STAGE = 'GOLLIFE'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;

-- NEW_JOB
SELECT 
    LIFE_STAGE,
    SUM(CRDSL_USE_AM) AS CRDSL_USE_AM,
    SUM(CNF_USE_AM) AS CNF_USE_AM
FROM card_transaction
WHERE LIFE_STAGE = 'NEW_JOB'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;

-- RETIRE
SELECT 
    LIFE_STAGE,
    SUM(CRDSL_USE_AM) AS CRDSL_USE_AM,
    SUM(CNF_USE_AM) AS CNF_USE_AM
FROM card_transaction
WHERE LIFE_STAGE = 'RETIRE'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;

-- SECLIFE
SELECT 
    LIFE_STAGE,
    SUM(CRDSL_USE_AM) AS CRDSL_USE_AM,
    SUM(CNF_USE_AM) AS CNF_USE_AM
FROM card_transaction
WHERE LIFE_STAGE = 'SECLIFE'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;

-- TEEN
SELECT 
    LIFE_STAGE,
    SUM(CRDSL_USE_AM) AS CRDSL_USE_AM,
    SUM(CNF_USE_AM) AS CNF_USE_AM
FROM card_transaction
WHERE LIFE_STAGE = 'TEEN'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;

-- UNI
SELECT 
    LIFE_STAGE,
    SUM(CRDSL_USE_AM) AS CRDSL_USE_AM,
    SUM(CNF_USE_AM) AS CNF_USE_AM
FROM card_transaction
WHERE LIFE_STAGE = 'UNI'
GROUP BY LIFE_STAGE
ORDER BY LIFE_STAGE;


/* =====================================================
   라이프스테이지별 회원등급 비율
   ===================================================== */
SELECT
  LIFE_STAGE,
  MBR_RK,
  COUNT(*) AS CNT,
  ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY LIFE_STAGE), 2) AS RATIO_PCT
FROM card_transaction
GROUP BY LIFE_STAGE, MBR_RK
ORDER BY LIFE_STAGE, RATIO_PCT DESC;

-- CHILD_BABY
SELECT
  LIFE_STAGE,
  MBR_RK,
  COUNT(*) AS CNT,
  ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY LIFE_STAGE), 2) AS RATIO_PCT
FROM card_transaction
WHERE LIFE_STAGE = 'CHILD_BABY'
GROUP BY LIFE_STAGE, MBR_RK
ORDER BY LIFE_STAGE, RATIO_PCT DESC;

-- CHILD_TEEN
SELECT
  LIFE_STAGE,
  MBR_RK,
  COUNT(*) AS CNT,
  ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY LIFE_STAGE), 2) AS RATIO_PCT
FROM card_transaction
WHERE LIFE_STAGE = 'CHILD_TEEN'
GROUP BY LIFE_STAGE, MBR_RK
ORDER BY LIFE_STAGE, RATIO_PCT DESC;

-- CHILD_UNI
SELECT
  LIFE_STAGE,
  MBR_RK,
  COUNT(*) AS CNT,
  ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY LIFE_STAGE), 2) AS RATIO_PCT
FROM card_transaction
WHERE LIFE_STAGE = 'CHILD_UNI'
GROUP BY LIFE_STAGE, MBR_RK
ORDER BY LIFE_STAGE, RATIO_PCT DESC;

-- GOLLIFE
SELECT
  LIFE_STAGE,
  MBR_RK,
  COUNT(*) AS CNT,
  ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY LIFE_STAGE), 2) AS RATIO_PCT
FROM card_transaction
WHERE LIFE_STAGE = 'GOLLIFE'
GROUP BY LIFE_STAGE, MBR_RK
ORDER BY LIFE_STAGE, RATIO_PCT DESC;

-- NEW_JOB
SELECT
  LIFE_STAGE,
  MBR_RK,
  COUNT(*) AS CNT,
  ROUND(    COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY LIFE_STAGE), 2) AS RATIO_PCT
FROM card_transaction
WHERE LIFE_STAGE = 'NEW_JOB'
GROUP BY LIFE_STAGE, MBR_RK
ORDER BY LIFE_STAGE, RATIO_PCT DESC;

-- RETIRE
SELECT
  LIFE_STAGE,
  MBR_RK,
  COUNT(*) AS CNT,
  ROUND(    COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY LIFE_STAGE), 2) AS RATIO_PCT
FROM card_transaction
WHERE LIFE_STAGE = 'RETIRE'
GROUP BY LIFE_STAGE, MBR_RK
ORDER BY LIFE_STAGE, RATIO_PCT DESC;

-- SECLIFE
SELECT
  LIFE_STAGE,
  MBR_RK,
  COUNT(*) AS CNT,
  ROUND(    COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY LIFE_STAGE), 2) AS RATIO_PCT
FROM card_transaction
WHERE LIFE_STAGE = 'SECLIFE'
GROUP BY LIFE_STAGE, MBR_RK
ORDER BY LIFE_STAGE, RATIO_PCT DESC;

-- TEEN
SELECT
  LIFE_STAGE,
  MBR_RK,
  COUNT(*) AS CNT,
  ROUND(    COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY LIFE_STAGE), 2) AS RATIO_PCT
FROM card_transaction
WHERE LIFE_STAGE = 'TEEN'
GROUP BY LIFE_STAGE, MBR_RK
ORDER BY LIFE_STAGE, RATIO_PCT DESC;

-- UNI
SELECT
  LIFE_STAGE,
  MBR_RK,
  COUNT(*) AS CNT,
  ROUND(    COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY LIFE_STAGE), 2) AS RATIO_PCT
FROM card_transaction
WHERE LIFE_STAGE = 'UNI'
GROUP BY LIFE_STAGE, MBR_RK
ORDER BY LIFE_STAGE, RATIO_PCT DESC;



