/* =====================================================
   라이프스테이지별 TOP 5 업종
   - 업종별 소비 금액 기준
   ===================================================== */

WITH agg AS (
  SELECT
    LIFE_STAGE,
    SUM(IFNULL(INTERIOR_AM, 0))  AS INTERIOR,
    SUM(IFNULL(INSUHOS_AM,  0))  AS INSUHOS,
    SUM(IFNULL(TRVL_AM,     0))  AS TRVL,
    SUM(IFNULL(CULTURE_AM,  0))  AS CULTURE,
    SUM(IFNULL(GROCERY_AM,  0))  AS GROCERY,
    SUM(IFNULL(HOS_AM,      0))  AS HOSPITAL,
    SUM(IFNULL(RESTRNT_AM,  0))  AS RESTAURANT,
    SUM(IFNULL(FUEL_AM,     0))  AS FUEL
  FROM card_transaction
  GROUP BY LIFE_STAGE
)
SELECT LIFE_STAGE, CATEGORY, TOTAL_AMT, RNK
FROM (
  SELECT
    LIFE_STAGE, CATEGORY, TOTAL_AMT,
    RANK() OVER (PARTITION BY LIFE_STAGE ORDER BY TOTAL_AMT DESC) AS RNK
     FROM (
      SELECT LIFE_STAGE, 'INTERIOR'   AS CATEGORY, INTERIOR   AS TOTAL_AMT FROM agg
    UNION ALL SELECT LIFE_STAGE, 'INSUHOS',    INSUHOS    FROM agg
    UNION ALL SELECT LIFE_STAGE, 'TRVL',       TRVL       FROM agg
    UNION ALL SELECT LIFE_STAGE, 'CULTURE',    CULTURE    FROM agg
    UNION ALL SELECT LIFE_STAGE, 'GROCERY',    GROCERY    FROM agg
    UNION ALL SELECT LIFE_STAGE, 'HOSPITAL',   HOSPITAL   FROM agg
    UNION ALL SELECT LIFE_STAGE, 'RESTAURANT', RESTAURANT FROM agg
    UNION ALL SELECT LIFE_STAGE, 'FUEL',       FUEL       FROM agg
  ) unpivoted
) ranked
WHERE RNK <= 5
ORDER BY LIFE_STAGE, RNK;
    